include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/fix/slim/.gitlab-ci/docker-ros.yml

variables:
  PLATFORM: amd64,arm64
  TARGET: dev,run
  BASE_IMAGE: rwthika/ros2:jazzy
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: ros2 launch point_cloud_fusion point_cloud_fusion.launch.py
  CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DREQUIRE_CUDA=ON"

  SLIM_BUILD_ARGS: >
    --env DOCKER_EPHEMERAL_USER=true
    --sensor-ipc-mode=proxy
    --continue-after=30
    --show-clogs
    --http-probe=false
    --include-path /etc/ld.so.cache
    --include-path /etc/ld.so.conf
    --include-path /etc/ld.so.conf.d
    --include-path /opt/ros
    --include-path /docker-ros/ws
    --include-path /usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudart.so
    --include-path /usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudart.so.12
    --include-path /usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudart.so.12.8.90
