include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml

variables:
  PLATFORM: amd64,arm64
  TARGET: dev,run
  ENABLE_SLIM: 'false'
  BASE_IMAGE: rwthika/ros2:jazzy
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: ros2 launch point_cloud_fusion point_cloud_fusion.launch.py
