FROM scratch

ARG IMAGE_VERSION

LABEL org.opencontainers.image.source="https://github.com/openads-project/point_cloud_fusion" \
      org.opencontainers.image.description="Point cloud data for the point cloud fusion demo" \
      org.opencontainers.image.version="${IMAGE_VERSION}"

COPY *.pcd /pcds/
