services:

  point-cloud-fusion:
    image: ghcr.io/openads-project/point_cloud_fusion:v1.4.0
    environment:
      # --- name ------
      NAMESPACE: /
      NAME: point_cloud_fusion
      # --- outputs ---
      POINT_CLOUD_TOPIC: ~/point_cloud
      # --- other -----
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      PARAMS: ${PARAMS:-/docker-ros/ws/install/point_cloud_fusion/share/point_cloud_fusion/config/params.yml}
      TRACE: ${TRACE:-false}
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch point_cloud_fusion point_cloud_fusion.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          params:=$${PARAMS} \
          trace:=$${TRACE} \
          point_cloud_topic:=$${POINT_CLOUD_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/point_cloud_fusion/share/point_cloud_fusion/config/params.yml
